import { db } from "../db";
import { config } from "../config";
import { logger } from "../utils/logger";
import { sha256 } from "../utils/hash.util";

// 認證服務 (Auth Service)
// 負責驗證用戶提供的 API Key 是否有效
export class AuthService {
  // 驗證密鑰 (Validate Key)
  static validateKey(key: string | undefined): boolean {
    if (!key) return false;

    // 如果存在 "Bearer " 前綴，則將其移除
    const token = key.startsWith("Bearer ") ? key.slice(7) : key;

    // 檢查是否與硬編碼的開發密鑰匹配
    if (token === config.hermesSecret) {
      return true;
    }

    // 從數據庫中查詢密鑰的哈希值
    const keyRecord = db.query(`SELECT id FROM hermes_keys WHERE key_hash = $key_hash`).get({ $key_hash: sha256(token) }) as { id: string } | undefined;

    if (keyRecord) {
      // 如果密鑰有效，更新其 lastUsedAt
      db.exec(`UPDATE hermes_keys SET lastUsedAt = ${Date.now()} WHERE id = '${keyRecord.id}'`);
      return true;
    }

    if (!keyRecord) {
      logger.warn("無效的訪問嘗試 (Invalid access attempt)", { tokenHash: sha256(token) });
    }

    return false;
  }

  // 生成新的密鑰 (只生成字符串，不負責存儲)
  static generateKey(): string {
    return `sk-${crypto.randomUUID()}`;
  }

  // 存儲給定的密鑰
  // 返回密鑰的 ID
  static storeKey(key: string, description: string = 'Generated by Admin'): string {
    const keyId = crypto.randomUUID();
    const keyHash = sha256(key);
    const createdAt = Date.now();

    // 在這裡添加檢查：如果哈希值已存在，則不重複插入
    const existingKey = db.query(`SELECT id FROM hermes_keys WHERE key_hash = $key_hash`).get({ $key_hash: keyHash }) as { id: string } | undefined;
    if (existingKey) {
        logger.warn(`[AuthService] Key with hash ${keyHash} already exists. Skipping insertion. Returning existing ID.`);
        return existingKey.id; // 返回已存在的 ID
    }

    logger.info(`[AuthService] Storing key: ${keyId} with hash ${keyHash} for description: ${description}`);

    db.query(`
      INSERT INTO hermes_keys (id, key_hash, description, createdAt)
      VALUES ($id, $key_hash, $description, $createdAt)
    `).run({
        $id: keyId,
        $key_hash: keyHash,
        $description: description,
        $createdAt: createdAt
    });
    return keyId;
  }

  // 獲取所有生成的密鑰 (支持過濾)
  static getGeneratedKeys(filters?: { description?: string, id?: string }): { id: string, description: string, createdAt: number, lastUsedAt: number | null }[] {
    const conditions: string[] = [];
    const params: Record<string, string> = {};

    if (filters?.description) {
      conditions.push(`description LIKE $description`);
      params.$description = `%${filters.description}%`;
    }

    if (filters?.id) {
      conditions.push(`id LIKE $id`);
      params.$id = `%${filters.id}%`;
    }

    const whereClause = conditions.length ? `WHERE ${conditions.join(" OR ")}` : "";

    return db.query(`SELECT id, description, createdAt, lastUsedAt FROM hermes_keys ${whereClause} ORDER BY createdAt DESC`).all(params) as any[];
  }

  // 刪除密鑰
  static deleteKey(id: string): boolean {
    const result = db.query(`DELETE FROM hermes_keys WHERE id = $id`).run({ $id: id });
    return result.changes > 0;
  }
}
