import { db } from "../db";
import { config } from "../config";
import { logger } from "../utils/logger";
import { sha256 } from "../utils/hash.util"; // [NEW] 導入自定義哈希工具

// 認證服務 (Auth Service)
// 負責驗證用戶提供的 API Key 是否有效
export class AuthService {
  // 驗證密鑰 (Validate Key)
  static validateKey(key: string | undefined): boolean {
    if (!key) return false;
    
    // 如果存在 "Bearer " 前綴，則將其移除
    const token = key.startsWith("Bearer ") ? key.slice(7) : key;
    
    // 檢查是否與硬編碼的開發密鑰匹配
    if (token === config.hermesSecret) {
      return true;
    }

    // 從數據庫中查詢密鑰的哈希值
    const keyRecord = db.query(`SELECT id FROM hermes_keys WHERE key_hash = '${sha256(token)}'`).get() as { id: string } | undefined;

    if (keyRecord) {
      // 如果密鑰有效，更新其 lastUsedAt
      db.exec(`UPDATE hermes_keys SET lastUsedAt = ${Date.now()} WHERE id = '${keyRecord.id}'`);
      return true;
    }
    
    if (!keyRecord) {
      logger.warn("無效的訪問嘗試 (Invalid access attempt)", { tokenHash: sha256(token) });
    }
    
    return false;
  }

  // 生成並存儲新的密鑰
  static generateKey(description: string = 'Generated by Admin'): string {
    const newKey = `sk-${crypto.randomUUID()}`;
    const keyHash = sha256(newKey);
    const createdAt = Date.now();

    db.exec(`
      INSERT INTO hermes_keys (id, key_hash, description, createdAt)
      VALUES ('${crypto.randomUUID()}', '${keyHash}', '${description}', ${createdAt})
    `);

    logger.info(`生成了新的密鑰: ${description}`);
    return newKey;
  }
  // 獲取所有生成的密鑰 (只顯示部分信息，不顯示哈希值)
  static getGeneratedKeys(): { id: string, description: string, createdAt: number, lastUsedAt: number | null }[] {
    return db.query(`SELECT id, description, createdAt, lastUsedAt FROM hermes_keys ORDER BY createdAt DESC`).all() as any[];
  }

  // 刪除密鑰
  static deleteKey(id: string): boolean {
    const result = db.query(`DELETE FROM hermes_keys WHERE id = '${id}'`).run();
    return result.changes > 0;
  }
}
